#ifndef NVIM_VIML_EXECUTOR_EXECUTOR_H
#define NVIM_VIML_EXECUTOR_EXECUTOR_H

#include <lua.h>

#include "nvim/api/private/helpers.h"
#include "nvim/func_attr.h"

// Generated by msgpack-gen.lua
void nlua_add_api_functions(lua_State *lstate) REAL_FATTR_NONNULL_ALL;

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "viml/executor/executor.h.generated.h"
#endif
#endif  // NVIM_VIML_EXECUTOR_EXECUTOR_H
