#ifndef NEOVIM_TRANSLATOR_TESTHELPERS_FGETLINE_H
#define NEOVIM_TRANSLATOR_TESTHELPERS_FGETLINE_H

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "translator/testhelpers/fgetline.h.generated.h"
#endif
#endif  // NEOVIM_TRANSLATOR_TESTHELPERS_FGETLINE_H
