#ifndef NEOVIM_TRANSLATOR_TESTHELPERS_PARSER_H
#define NEOVIM_TRANSLATOR_TESTHELPERS_PARSER_H

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "translator/testhelpers/parser.h.generated.h"
#endif
#endif  // NEOVIM_TRANSLATOR_TESTHELPERS_PARSER_H
