#ifndef NEOVIM_TRANSLATOR_TESTHELPERS_TRANSLATOR_H
#define NEOVIM_TRANSLATOR_TESTHELPERS_TRANSLATOR_H

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "translator/testhelpers/translator.h"
#endif
#endif  // NEOVIM_TRANSLATOR_TESTHELPERS_TRANSLATOR_H
