#ifndef NEOVIM_VIML_TESTHELPERS_TRANSLATOR_H
#define NEOVIM_VIML_TESTHELPERS_TRANSLATOR_H

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "viml/testhelpers/translator.h"
#endif
#endif  // NEOVIM_VIML_TESTHELPERS_TRANSLATOR_H
