/* vi:set ts=8 sts=4 sw=4:
 *
 * VIM - Vi IMproved	by Bram Moolenaar
 *
 * Do ":help uganda"  in Vim to read copying and usage conditions.
 * Do ":help credits" in Vim to see a list of people who contributed.
 */

/*
 * This file defines the Ex commands.
 * When DO_DECLARE_EXCMD is defined, the table with ex command names and
 * options results.
 * When DO_DECLARE_EXCMD is NOT defined, the enum with all the Ex commands
 * results.
 * This clever trick was invented by Ron Aaron.
 */

/*
 * When adding an Ex command:
 * 1. Add an entry in the table below.  Keep it sorted on the shortest
 *    version of the command name that works.  If it doesn't start with a
 *    lower case letter, add it at the end.
 * 2. Add a "case: kCmdXxx" in the big switch in ex_docmd.c.
 * 3. Add an entry in the index for Ex commands at ":help ex-cmd-index".
 * 4. Add documentation in ../doc/xxx.txt.  Add a tag for both the short and
 *    long name of the command.
 */

#if (defined(DO_DECLARE_EXCMD) && !defined(NEOVIM_CMD_DEF_H_DECLARED)) || (!defined(DO_DECLARE_EXCMD) && !defined(NEOVIM_CMD_DEF_H_DEFINED_ENUM))

#include <stdint.h>
#include "cmd_arg_constants.h"

#ifdef DO_DECLARE_EXCMD
# define NEOVIM_CMD_DEF_H_DECLARED
#else
# define NEOVIM_CMD_DEF_H_DEFINED_ENUM
#endif

#ifdef RANGE
# undef RANGE                   /* SASC on Amiga defines it */
#endif

#define RANGE           0x001   /* allow a linespecs */
#define BANG            0x002   /* allow a ! after the command name */
#define EXTRA           0x004   /* allow extra args after command name */
#define XFILE           0x008   /* expand wildcards in extra part */
#define NOSPC           0x010   /* no spaces allowed in the extra part */
#define DFLALL          0x020   /* default file range is 1,$ */
#define WHOLEFOLD       0x040   /* extend range to include whole fold also
                                   when less than two numbers given */
#define NEEDARG         0x080   /* argument required */
#define TRLBAR          0x100   /* check for trailing vertical bar */
#define REGSTR          0x200   /* allow "x for register designation */
#define COUNT           0x400   /* allow count in argument, after command */
#define NOTRLCOM        0x800   /* no trailing comment allowed */
#define ZEROR          0x1000   /* zero line number allowed */
#define USECTRLV       0x2000   /* do not remove CTRL-V from argument */
#define NOTADR         0x4000   /* number before command is not an address */
#define EDITCMD        0x8000   /* allow "+command" argument */
#define BUFNAME       0x10000L  /* accepts buffer name */
#define BUFUNL        0x20000L  /* accepts unlisted buffer too */
#define ARGOPT        0x40000L  /* allow "++opt=val" argument */
#define SBOXOK        0x80000L  /* allowed in the sandbox */
#define CMDWIN       0x100000L  /* allowed in cmdline window */
#define MODIFY       0x200000L  /* forbidden in non-'modifiable' buffer */
#define EXFLAGS      0x400000L  /* allow flags after count in argument */

#define ISMODIFIER   0x800000L  /* is a modifier command */

#define FILES   (XFILE | EXTRA) /* multiple extra files allowed */
#define WORD1   (EXTRA | NOSPC) /* one extra word allowed */
#define FILE1   (FILES | NOSPC) /* 1 file allowed, defaults to current file */

#ifndef DO_DECLARE_EXCMD
typedef struct command_definition CommandDefinition;
#endif

/*
 * This array maps ex command names to command codes.
 * The order in which command names are listed below is significant --
 * ambiguous abbreviations are always resolved to be the first possible match
 * (e.g. "r" is taken to mean "read", not "rewind", because "read" comes
 * before "rewind").
 * Not supported commands are included to avoid ambiguities.
 */
#ifdef EX
# undef EX          /* just in case */
#endif
#ifdef DO_DECLARE_EXCMD
# define EX(idx, name, func, last_arg, args, flags) \
    {(char_u *)name, \
     (uint_least32_t) (flags), \
     last_arg + 1, \
     (CommandArgType[]) args}

static struct command_definition {
  char_u      *cmd_name;      // name of the command
  uint_least32_t cmd_argt;    // flags declared above
  size_t num_args;            // number of arguments
  CommandArgType *arg_types;  // argument types
}
cmddefs[] =
#else
# define EX(idx, name, func, last_arg, args, flags) idx
typedef enum
#endif
{
  EX(kCmdAppend,          "append",       ex_append,
     ARG_APPEND_LINES, ARGS_APPEND,
     BANG|RANGE|ZEROR|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdAbbreviate,      "abbreviate",   ex_abbreviate,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdAbclear,         "abclear",      ex_abclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdAboveleft,       "aboveleft",    ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdAll,             "all",          ex_all,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdAmenu,           "amenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdAnoremenu,       "anoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdArgs,            "args",         ex_args,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArgadd,          "argadd",       ex_argadd,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|RANGE|NOTADR|ZEROR|FILES|TRLBAR),
  EX(kCmdArgdelete,       "argdelete",    ex_argdelete,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|FILES|TRLBAR),
  EX(kCmdArgdo,           "argdo",        ex_listdo,
     ARG_DO_CMD, ARGS_DO,
     BANG|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdArgedit,         "argedit",      ex_argedit,
     ARG_E_CMD, ARGS_E,
     BANG|NEEDARG|RANGE|NOTADR|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArgglobal,       "argglobal",    ex_args,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArglocal,        "arglocal",     ex_args,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArgument,        "argument",     ex_argument,
     ARG_E_CMD, ARGS_E,
     BANG|RANGE|NOTADR|COUNT|EXTRA|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdAscii,           "ascii",        do_ascii,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdAutocmd,         "autocmd",      ex_autocmd,
     ARG_AU_CMD, ARGS_AU,
     BANG|EXTRA|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdAugroup,         "augroup",      ex_autocmd,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdAunmenu,         "aunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdBuffer,          "buffer",       ex_buffer,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|TRLBAR),
  EX(kCmdBNext,           "bNext",        ex_bprevious,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBall,            "ball",         ex_buffer_all,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  /* +lnum will be recorded in range */
  EX(kCmdBadd,            "badd",         ex_edit,
     ARG_SO_FILES, ARGS_SO,
     NEEDARG|FILE1|EDITCMD|TRLBAR|CMDWIN),
  EX(kCmdBdelete,         "bdelete",      ex_bunload,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR),
  EX(kCmdBehave,          "behave",       ex_behave,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdBelowright,      "belowright",   ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdBfirst,          "bfirst",       ex_brewind,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|TRLBAR),
  EX(kCmdBlast,           "blast",        ex_blast,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|TRLBAR),
  EX(kCmdBmodified,       "bmodified",    ex_bmodified,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBnext,           "bnext",        ex_bnext,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBotright,        "botright",     ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdBprevious,       "bprevious",    ex_bprevious,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBrewind,         "brewind",      ex_brewind,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|TRLBAR),
  EX(kCmdBreak,           "break",        ex_break,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdBreakadd,        "breakadd",     ex_breakadd,
     ARG_BREAK_NAME, ARGS_BREAK,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdBreakdel,        "breakdel",     ex_breakdel,
     ARG_BREAK_NAME, ARGS_BREAK,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdBreaklist,       "breaklist",    ex_breaklist,
     ARG_NO_ARGS, ARGS_NO,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdBrowse,          "browse",       ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|CMDWIN | ISMODIFIER),
  EX(kCmdBuffers,         "buffers",      buflist_list,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdBufdo,           "bufdo",        ex_listdo,
     ARG_DO_CMD, ARGS_DO,
     BANG|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdBunload,         "bunload",      ex_bunload,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR),
  EX(kCmdBwipeout,        "bwipeout",     ex_bunload,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|TRLBAR),
  EX(kCmdChange,          "change",       ex_change,
     ARG_APPEND_LINES, ARGS_APPEND,
     BANG|WHOLEFOLD|RANGE|COUNT|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdCNext,           "cNext",        ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCNfile,          "cNfile",       ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCabbrev,         "cabbrev",      ex_abbreviate,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCabclear,        "cabclear",     ex_abclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdCaddbuffer,      "caddbuffer",   ex_cbuffer,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdCaddexpr,        "caddexpr",     ex_cexpr,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdCaddfile,        "caddfile",     ex_cfile,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdCall,            "call",         ex_call,
     ARG_EXPR_EXPR, ARGS_EXPR,
     RANGE|NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdCatch,           "catch",        ex_catch,
     ARG_REG_REG, ARGS_REG,
     EXTRA|SBOXOK|CMDWIN),
  EX(kCmdCbuffer,         "cbuffer",      ex_cbuffer,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdCc,              "cc",           ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCclose,          "cclose",       ex_cclose,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdCd,              "cd",           ex_cd,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdCenter,          "center",       ex_align,
     ARG_CENTER_WIDTH, ARGS_CENTER,
     TRLBAR|RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdCexpr,           "cexpr",        ex_cexpr,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR|BANG),
  EX(kCmdCfile,           "cfile",        ex_cfile,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1|BANG),
  EX(kCmdCfirst,          "cfirst",       ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCgetfile,        "cgetfile",     ex_cfile,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdCgetbuffer,      "cgetbuffer",   ex_cbuffer,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdCgetexpr,        "cgetexpr",     ex_cexpr,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdChdir,           "chdir",        ex_cd,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdChanges,         "changes",      ex_changes,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdCheckpath,       "checkpath",    ex_checkpath,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG|CMDWIN),
  EX(kCmdChecktime,       "checktime",    ex_checktime,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR),
  EX(kCmdClist,           "clist",        qf_list,
     ARG_CLIST_LAST, ARGS_CLIST,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdClast,           "clast",        ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdClose,           "close",        ex_close,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdCmap,            "cmap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCmapclear,       "cmapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdCmenu,           "cmenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCnext,           "cnext",        ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCnewer,          "cnewer",       qf_age,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdCnfile,          "cnfile",       ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCnoremap,        "cnoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCnoreabbrev,     "cnoreabbrev",  ex_abbreviate,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCnoremenu,       "cnoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCopy,            "copy",         ex_copymove,
     ARG_ADDR_ADDR, ARGS_ADDR,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdColder,          "colder",       qf_age,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdColorscheme,     "colorscheme",  ex_colorscheme,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdCommand,         "command",      ex_command,
     ARG_CMD_CMD, ARGS_CMD,
     EXTRA|BANG|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdComclear,        "comclear",     ex_comclear,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdCompiler,        "compiler",     ex_compiler,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1|CMDWIN),
  EX(kCmdContinue,        "continue",     ex_continue,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdConfirm,         "confirm",      ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|CMDWIN | ISMODIFIER),
  EX(kCmdCopen,           "copen",        ex_copen,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdCprevious,       "cprevious",    ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCpfile,          "cpfile",       ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCquit,           "cquit",        ex_cquit,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG),
  EX(kCmdCrewind,         "crewind",      ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCscope,          "cscope",       do_cscope,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM|XFILE),
  EX(kCmdCstag,           "cstag",        do_cstag,
     ARG_CSTAG_TAG, ARGS_CSTAG,
     BANG|TRLBAR|WORD1),
  EX(kCmdCunmap,          "cunmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCunabbrev,       "cunabbrev",    ex_abbreviate,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCunmenu,         "cunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCwindow,         "cwindow",      ex_cwindow,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdDelete,          "delete",       ex_operators,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|REGSTR|COUNT|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdDelmarks,        "delmarks",     ex_delmarks,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDebug,           "debug",        ex_debug,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdDebuggreedy,     "debuggreedy",  ex_debuggreedy,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|ZEROR|TRLBAR|CMDWIN),
  EX(kCmdDelcommand,      "delcommand",   ex_delcommand,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdDelfunction,     "delfunction",  ex_delfunction,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|WORD1|CMDWIN),
  EX(kCmdDisplay,         "display",      ex_display,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdDiffupdate,      "diffupdate",   ex_diffupdate,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdDiffget,         "diffget",      ex_diffgetput,
     ARG_SO_FILES, ARGS_SO,
     RANGE|EXTRA|TRLBAR|MODIFY),
  EX(kCmdDiffoff,         "diffoff",      ex_diffoff,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdDiffpatch,       "diffpatch",    ex_diffpatch,
     ARG_SO_FILES, ARGS_SO,
     EXTRA|FILE1|TRLBAR|MODIFY),
  EX(kCmdDiffput,         "diffput",      ex_diffgetput,
     ARG_SO_FILES, ARGS_SO,
     RANGE|EXTRA|TRLBAR),
  EX(kCmdDiffsplit,       "diffsplit",    ex_diffsplit,
     ARG_SO_FILES, ARGS_SO,
     EXTRA|FILE1|TRLBAR),
  EX(kCmdDiffthis,        "diffthis",     ex_diffthis,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdDigraphs,        "digraphs",     ex_digraphs,
     ARG_DIG_CHARS, ARGS_DIG,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDjump,           "djump",        ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdDlist,           "dlist",        ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdDoautocmd,       "doautocmd",    ex_doautocmd,
     ARG_DOAU_FNAME, ARGS_DOAU,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDoautoall,       "doautoall",    ex_doautoall,
     ARG_DOAU_FNAME, ARGS_DOAU,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDrop,            "drop",         ex_drop,
     ARG_E_CMD, ARGS_E,
     FILES|EDITCMD|NEEDARG|ARGOPT|TRLBAR),
  EX(kCmdDsearch,         "dsearch",      ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdDsplit,          "dsplit",       ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdEdit,            "edit",         ex_edit,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdEarlier,         "earlier",      ex_later,
     ARG_NAME_NAME, ARGS_NAME,
     TRLBAR|EXTRA|NOSPC|CMDWIN),
  EX(kCmdEcho,            "echo",         ex_echo,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEchoerr,         "echoerr",      ex_execute,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEchohl,          "echohl",       ex_echohl,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEchomsg,         "echomsg",      ex_execute,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEchon,           "echon",        ex_echo,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdElse,            "else",         ex_else,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdElseif,          "elseif",       ex_else,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEmenu,           "emenu",        ex_emenu,
     ARG_MENU_TEXT, ARGS_MENU,
     NEEDARG|EXTRA|TRLBAR|NOTRLCOM|RANGE|NOTADR|CMDWIN),
  EX(kCmdEndif,           "endif",        ex_endif,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEndfunction,     "endfunction",  ex_endfunction,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdEndfor,          "endfor",       ex_endwhile,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEndtry,          "endtry",       ex_endtry,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEndwhile,        "endwhile",     ex_endwhile,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEnew,            "enew",         ex_edit,
     ARG_E_CMD, ARGS_E,
     BANG|TRLBAR),
  EX(kCmdEx,              "ex",           ex_edit,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdExecute,         "execute",      ex_execute,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdExit,            "exit",         ex_exit,
     ARG_EXIT_ENC, ARGS_EXIT,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN),
  EX(kCmdExusage,         "exusage",      ex_exusage,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdFile,            "file",         ex_file,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|NOTADR|ZEROR|BANG|FILE1|TRLBAR),
  EX(kCmdFiles,           "files",        buflist_list,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdFiletype,        "filetype",     ex_filetype,
     ARG_FT_FLAGS, ARGS_FT,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdFind,            "find",         ex_find,
     ARG_E_CMD, ARGS_E,
     RANGE|NOTADR|BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdFinally,         "finally",      ex_finally,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFinish,          "finish",       ex_finish,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFirst,           "first",        ex_rewind,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdFixdel,          "fixdel",       do_fixdel,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdFold,            "fold",         ex_fold,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFoldclose,       "foldclose",    ex_foldopen,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|BANG|WHOLEFOLD|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFolddoopen,      "folddoopen",   ex_folddo,
     ARG_DO_CMD, ARGS_DO,
     RANGE|DFLALL|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdFolddoclosed,    "folddoclosed", ex_folddo,
     ARG_DO_CMD, ARGS_DO,
     RANGE|DFLALL|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdFoldopen,        "foldopen",     ex_foldopen,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|BANG|WHOLEFOLD|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFor,             "for",          ex_while,
     ARG_ASSIGN_RHS, ARGS_ASSIGN,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdFunction,        "function",     ex_function,
     ARG_FUNC_BODY, ARGS_FUNC,
     EXTRA|BANG|CMDWIN),
  EX(kCmdGlobal,          "global",       ex_global,
     ARG_G_CMD, ARGS_G,
     RANGE|WHOLEFOLD|BANG|EXTRA|DFLALL|SBOXOK|CMDWIN),
  EX(kCmdGoto,            "goto",         ex_goto,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdGrep,            "grep",         ex_make,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdGrepadd,         "grepadd",      ex_make,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdGui,             "gui",          ex_gui,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR|CMDWIN),
  EX(kCmdGvim,            "gvim",         ex_gui,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR|CMDWIN),
  EX(kCmdHelp,            "help",         ex_help,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|EXTRA|NOTRLCOM),
  EX(kCmdHelpfind,        "helpfind",     ex_helpfind,
     ARG_NO_ARGS, ARGS_NO,
     EXTRA|NOTRLCOM),
  EX(kCmdHelpgrep,        "helpgrep",     ex_helpgrep,
     ARG_HELPG_LANG, ARGS_HELPG,
     EXTRA|NOTRLCOM|NEEDARG),
  /* ++t is in count */
  EX(kCmdHelptags,        "helptags",     ex_helptags,
     ARG_SO_FILES, ARGS_SO,
     NEEDARG|FILES|TRLBAR|CMDWIN),
  EX(kCmdHardcopy,        "hardcopy",     ex_hardcopy,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|COUNT|EXTRA|TRLBAR|DFLALL|BANG),
  EX(kCmdHighlight,       "highlight",    ex_highlight,
     ARG_HI_GUISP, ARGS_HI,
     BANG|EXTRA|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdHide,            "hide",         ex_hide,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     BANG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdHistory,         "history",      ex_history,
     ARG_HIST_LAST, ARGS_HIST,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdInsert,          "insert",       ex_append,
     ARG_APPEND_LINES, ARGS_APPEND,
     BANG|RANGE|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdIabbrev,         "iabbrev",      ex_abbreviate,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIabclear,        "iabclear",     ex_abclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdIf,              "if",           ex_if,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdIjump,           "ijump",        ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdIlist,           "ilist",        ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdImap,            "imap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdImapclear,       "imapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdImenu,           "imenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdInoremap,        "inoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdInoreabbrev,     "inoreabbrev",  ex_abbreviate,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdInoremenu,       "inoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIntro,           "intro",        ex_intro,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdIsearch,         "isearch",      ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdIsplit,          "isplit",       ex_findpat,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdIunmap,          "iunmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIunabbrev,       "iunabbrev",    ex_abbreviate,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIunmenu,         "iunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdJoin,            "join",         ex_join,
     ARG_LIST_FLAGS, ARGS_LIST,
     BANG|RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdJumps,           "jumps",        ex_jumps,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdK,               "k",            ex_mark,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WORD1|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdKeepmarks,       "keepmarks",    ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdKeepjumps,       "keepjumps",    ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdKeeppatterns,    "keeppatterns", ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdKeepalt,         "keepalt",      ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdList,            "list",         ex_print,
     ARG_LIST_FLAGS, ARGS_LIST,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdLNext,           "lNext",        ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLNfile,          "lNfile",       ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLast,            "last",         ex_last,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdLanguage,        "language",     ex_language,
     ARG_LANG_LANG, ARGS_LANG,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLaddexpr,        "laddexpr",     ex_cexpr,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdLaddbuffer,      "laddbuffer",   ex_cbuffer,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdLaddfile,        "laddfile",     ex_cfile,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdLater,           "later",        ex_later,
     ARG_NAME_NAME, ARGS_NAME,
     TRLBAR|EXTRA|NOSPC|CMDWIN),
  EX(kCmdLbuffer,         "lbuffer",      ex_cbuffer,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdLcd,             "lcd",          ex_cd,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdLchdir,          "lchdir",       ex_cd,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdLclose,          "lclose",       ex_cclose,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLcscope,         "lcscope",      do_cscope,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM|XFILE),
  EX(kCmdLeft,            "left",         ex_align,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdLeftabove,       "leftabove",    ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdLet,             "let",          ex_let,
     ARG_ASSIGN_RHS, ARGS_ASSIGN,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdLexpr,           "lexpr",        ex_cexpr,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR|BANG),
  EX(kCmdLfile,           "lfile",        ex_cfile,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1|BANG),
  EX(kCmdLfirst,          "lfirst",       ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLgetfile,        "lgetfile",     ex_cfile,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdLgetbuffer,      "lgetbuffer",   ex_cbuffer,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdLgetexpr,        "lgetexpr",     ex_cexpr,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdLgrep,           "lgrep",        ex_make,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLgrepadd,        "lgrepadd",     ex_make,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLhelpgrep,       "lhelpgrep",    ex_helpgrep,
     ARG_HELPG_LANG, ARGS_HELPG,
     EXTRA|NOTRLCOM|NEEDARG),
  EX(kCmdLl,              "ll",           ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLlast,           "llast",        ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLlist,           "llist",        qf_list,
     ARG_CLIST_LAST, ARGS_CLIST,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLmap,            "lmap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdLmapclear,       "lmapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLmake,           "lmake",        ex_make,
     ARG_SHELL_ARGS, ARGS_SHELL,
     BANG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLnoremap,        "lnoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdLnext,           "lnext",        ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLnewer,          "lnewer",       qf_age,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLnfile,          "lnfile",       ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLoadview,        "loadview",     ex_loadview,
     ARG_NO_ARGS, ARGS_NO,
     FILE1|TRLBAR),
  EX(kCmdLoadkeymap,      "loadkeymap",   ex_loadkeymap,
     ARG_APPEND_LINES, ARGS_APPEND,
     CMDWIN),
  EX(kCmdLockmarks,       "lockmarks",    ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdLockvar,         "lockvar",      ex_lockvar,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdLolder,          "lolder",       qf_age,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLopen,           "lopen",        ex_copen,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLprevious,       "lprevious",    ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLpfile,          "lpfile",       ex_cnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLrewind,         "lrewind",      ex_cc,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLtag,            "ltag", ex_tag,
     ARG_REG_REG, ARGS_REG,
     NOTADR|TRLBAR|BANG|WORD1),
  EX(kCmdLua,             "lua",          ex_lua,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdLuado,           "luado",        ex_luado,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdLuafile,         "luafile",      ex_luafile,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdLunmap,          "lunmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdLvimgrep,        "lvimgrep",     ex_vimgrep,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLvimgrepadd,     "lvimgrepadd",  ex_vimgrep,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLwindow,         "lwindow",      ex_cwindow,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLs,              "ls",           buflist_list,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdMove,            "move",         ex_copymove,
     ARG_ADDR_ADDR, ARGS_ADDR,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdMark,            "mark",         ex_mark,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WORD1|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdMake,            "make",         ex_make,
     ARG_SHELL_ARGS, ARGS_SHELL,
     BANG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdMap,             "map",          ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdMapclear,        "mapclear",     ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|BANG|TRLBAR|CMDWIN),
  EX(kCmdMarks,           "marks",        do_marks,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdMatch,           "match",        ex_match,
     ARG_MATCH_REG, ARGS_MATCH,
     RANGE|NOTADR|EXTRA|CMDWIN),
  EX(kCmdMenu,            "menu",         ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdMenutranslate,   "menutranslate", ex_menutranslate,
     ARG_MT_TO, ARGS_MT,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdMessages,        "messages",     ex_messages,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdMkexrc,          "mkexrc",       ex_mkrc,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdMksession,       "mksession",    ex_mkrc,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR),
  EX(kCmdMkspell,         "mkspell",      ex_mkspell,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdMkvimrc,         "mkvimrc",      ex_mkrc,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdMkview,          "mkview",       ex_mkrc,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR),
  EX(kCmdMode,            "mode",         ex_mode,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdMzscheme,        "mzscheme",     ex_mzscheme,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|DFLALL|NEEDARG|CMDWIN|SBOXOK),
  EX(kCmdMzfile,          "mzfile",       ex_mzfile,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdNext,            "next",         ex_next,
     ARG_FIRST_CMD, ARGS_FIRST,
     RANGE|NOTADR|BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdNbkey,           "nbkey",        ex_nbkey,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTADR|NEEDARG),
  EX(kCmdNbclose,         "nbclose",      ex_nbclose,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdNbstart,         "nbstart",      ex_nbstart,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdNew,             "new",          ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdNmap,            "nmap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNmapclear,       "nmapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdNmenu,           "nmenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNnoremap,        "nnoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNnoremenu,       "nnoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNoremap,         "noremap",      ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNoautocmd,       "noautocmd",    ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdNohlsearch,      "nohlsearch",   ex_nohlsearch,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdNoreabbrev,      "noreabbrev",   ex_abbreviate,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNoremenu,        "noremenu",     ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNormal,          "normal",       ex_normal,
     ARG_NORMAL_STR, ARGS_NORMAL,
     RANGE|BANG|EXTRA|NEEDARG|NOTRLCOM|USECTRLV|SBOXOK|CMDWIN),
  EX(kCmdNumber,          "number",       ex_print,
     ARG_LIST_FLAGS, ARGS_LIST,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdNunmap,          "nunmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNunmenu,         "nunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOpen,            "open",         ex_open,
     ARG_REG_REG, ARGS_REG,
     RANGE|BANG|EXTRA),
  EX(kCmdOldfiles,        "oldfiles",     ex_oldfiles,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdOmap,            "omap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOmapclear,       "omapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdOmenu,           "omenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOnly,            "only",         ex_only,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdOnoremap,        "onoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOnoremenu,       "onoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOptions,         "options",      ex_options,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdOunmap,          "ounmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOunmenu,         "ounmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOwnsyntax,       "ownsyntax",    ex_ownsyntax,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdPrint,           "print",        ex_print,
     ARG_LIST_FLAGS, ARGS_LIST,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|SBOXOK),
  EX(kCmdPclose,          "pclose",       ex_pclose,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdPerl,            "perl",         ex_perl,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|DFLALL|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdPerldo,          "perldo",       ex_perldo,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|EXTRA|DFLALL|NEEDARG|CMDWIN),
  EX(kCmdPedit,           "pedit",        ex_pedit,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdPop,             "pop",          ex_tag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|COUNT|TRLBAR|ZEROR),
  EX(kCmdPopup,           "popup",        ex_popup,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|EXTRA|BANG|TRLBAR|NOTRLCOM|CMDWIN),
  EX(kCmdPpop,            "ppop",         ex_ptag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|COUNT|TRLBAR|ZEROR),
  EX(kCmdPreserve,        "preserve",     ex_preserve,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdPrevious,        "previous",     ex_previous,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdPromptfind,      "promptfind",   gui_mch_find_dialog,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|CMDWIN),
  EX(kCmdPromptrepl,      "promptrepl",   gui_mch_replace_dialog,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|CMDWIN),
  EX(kCmdProfile,         "profile",      ex_profile,
     ARG_PROFILE_PAT, ARGS_PROFILE,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdProfdel,         "profdel",      ex_breakdel,
     ARG_PROFILE_PAT, ARGS_PROFILE,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdPsearch,         "psearch",      ex_psearch,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|WHOLEFOLD|DFLALL|EXTRA),
  EX(kCmdPtag,            "ptag",         ex_ptag,
     ARG_REG_REG, ARGS_REG,
     RANGE|NOTADR|BANG|WORD1|TRLBAR|ZEROR),
  EX(kCmdPtNext,          "ptNext",       ex_ptag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtfirst,         "ptfirst",      ex_ptag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtjump,          "ptjump",       ex_ptag,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdPtlast,          "ptlast",       ex_ptag,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdPtnext,          "ptnext",       ex_ptag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtprevious,      "ptprevious",   ex_ptag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtrewind,        "ptrewind",     ex_ptag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtselect,        "ptselect",     ex_ptag,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdPut,             "put",          ex_put,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|BANG|REGSTR|TRLBAR|ZEROR|CMDWIN|MODIFY),
  EX(kCmdPwd,             "pwd",          ex_pwd,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdPython,          "python",       ex_python,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPydo,            "pydo",         ex_pydo,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPyfile,          "pyfile",       ex_pyfile,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdPy3,             "py3",          ex_py3,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPy3do,           "py3do",        ex_py3do,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPython3,         "python3",      ex_py3,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPy3file,         "py3file",      ex_py3file,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdQuit,            "quit",         ex_quit,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdQuitall,         "quitall",      ex_quit_all,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR),
  EX(kCmdQall,            "qall",         ex_quit_all,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdRead,            "read",         ex_read,
     ARG_W_SHELL, ARGS_W,
     BANG|RANGE|WHOLEFOLD|FILE1|ARGOPT|TRLBAR|ZEROR|CMDWIN|MODIFY),
  EX(kCmdRecover,         "recover",      ex_recover,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR),
  EX(kCmdRedo,            "redo",         ex_redo,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdRedir,           "redir",        ex_redir,
     ARG_REDIR_VAR, ARGS_REDIR,
     BANG|FILES|TRLBAR|CMDWIN),
  EX(kCmdRedraw,          "redraw",       ex_redraw,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdRedrawstatus,    "redrawstatus", ex_redrawstatus,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdRegisters,       "registers",    ex_display,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|TRLBAR|CMDWIN),
  EX(kCmdResize,          "resize",       ex_resize,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|TRLBAR|WORD1),
  EX(kCmdRetab,           "retab",        ex_retab,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|RANGE|WHOLEFOLD|DFLALL|BANG|WORD1|CMDWIN|MODIFY),
  EX(kCmdReturn,          "return",       ex_return,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdRewind,          "rewind",       ex_rewind,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdRight,           "right",        ex_align,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdRightbelow,      "rightbelow",   ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdRuntime,         "runtime",      ex_runtime,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|FILES|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdRuby,            "ruby",         ex_ruby,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdRubydo,          "rubydo",       ex_rubydo,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdRubyfile,        "rubyfile",     ex_rubyfile,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdRundo,           "rundo",        ex_rundo,
     ARG_SO_FILES, ARGS_SO,
     NEEDARG|FILE1),
  EX(kCmdRviminfo,        "rviminfo",     ex_viminfo,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdSubstitute,      "substitute",   do_sub,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdSNext,           "sNext",        ex_previous,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSargument,       "sargument",    ex_argument,
     ARG_FIRST_CMD, ARGS_FIRST,
     BANG|RANGE|NOTADR|COUNT|EXTRA|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSall,            "sall",         ex_all,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSandbox,         "sandbox",      ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdSaveas,          "saveas",       ex_write,
     ARG_WN_ENC, ARGS_WN,
     BANG|DFLALL|FILE1|ARGOPT|CMDWIN|TRLBAR),
  EX(kCmdSbuffer,         "sbuffer",      ex_buffer,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|TRLBAR),
  EX(kCmdSbNext,          "sbNext",       ex_bprevious,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSball,           "sball",        ex_buffer_all,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbfirst,         "sbfirst",      ex_brewind,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSblast,          "sblast",       ex_blast,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSbmodified,      "sbmodified",   ex_bmodified,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbnext,          "sbnext",       ex_bnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbprevious,      "sbprevious",   ex_bprevious,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbrewind,        "sbrewind",     ex_brewind,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdScriptnames,     "scriptnames",  ex_scriptnames,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdScriptencoding,  "scriptencoding", ex_scriptencoding,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdScscope,         "scscope",      do_scscope,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM),
  EX(kCmdSet,             "set",          ex_set,
     ARG_SET_VALUES, ARGS_SET,
     TRLBAR|EXTRA|CMDWIN|SBOXOK),
  EX(kCmdSetfiletype,     "setfiletype",  ex_setfiletype,
     ARG_NAME_NAME, ARGS_NAME,
     TRLBAR|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdSetglobal,       "setglobal",    ex_set,
     ARG_SET_VALUES, ARGS_SET,
     TRLBAR|EXTRA|CMDWIN|SBOXOK),
  EX(kCmdSetlocal,        "setlocal",     ex_set,
     ARG_SET_VALUES, ARGS_SET,
     TRLBAR|EXTRA|CMDWIN|SBOXOK),
  EX(kCmdSfind,           "sfind",        ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSfirst,          "sfirst",       ex_rewind,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdShell,           "shell",        ex_shell,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdSimalt,          "simalt",       ex_simalt,
     ARG_SIMALT_CHAR, ARGS_SIMALT,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdSign,            "sign",         ex_sign,
     ARG_SUBCMD, ARGS_SUBCMD,
     NEEDARG|RANGE|NOTADR|EXTRA|CMDWIN),
  EX(kCmdSilent,          "silent",       ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|BANG|NOTRLCOM|SBOXOK|CMDWIN | ISMODIFIER),
  EX(kCmdSleep,           "sleep",        ex_sleep,
     ARG_SLEEP_SECONDS, ARGS_SLEEP,
     RANGE|NOTADR|COUNT|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdSlast,           "slast",        ex_last,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSmagic,          "smagic",       ex_submagic,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdSmap,            "smap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSmapclear,       "smapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdSmenu,           "smenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSnext,           "snext",        ex_next,
     ARG_E_CMD, ARGS_E,
     RANGE|NOTADR|BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSniff,           "sniff",        ex_sniff,
     ARG_SNIFF_SYMBOL, ARGS_SNIFF,
     EXTRA|TRLBAR),
  EX(kCmdSnomagic,        "snomagic",     ex_submagic,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdSnoremap,        "snoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSnoremenu,       "snoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSource,          "source",       ex_source,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdSort,            "sort",         ex_sort,
     ARG_SORT_REG, ARGS_SORT,
     RANGE|DFLALL|WHOLEFOLD|BANG|EXTRA|NOTRLCOM|MODIFY),
  EX(kCmdSplit,           "split",        ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSpellgood,       "spellgood",    ex_spell,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|RANGE|NOTADR|NEEDARG|EXTRA|TRLBAR),
  EX(kCmdSpelldump,       "spelldump",    ex_spelldump,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdSpellinfo,       "spellinfo",    ex_spellinfo,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSpellrepall,     "spellrepall",  ex_spellrepall,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSpellundo,       "spellundo",    ex_spell,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|RANGE|NOTADR|NEEDARG|EXTRA|TRLBAR),
  EX(kCmdSpellwrong,      "spellwrong",   ex_spell,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|RANGE|NOTADR|NEEDARG|EXTRA|TRLBAR),
  EX(kCmdSprevious,       "sprevious",    ex_previous,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSrewind,         "srewind",      ex_rewind,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdStop,            "stop",         ex_stop,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG|CMDWIN),
  EX(kCmdStag,            "stag",         ex_stag,
     ARG_REG_REG, ARGS_REG,
     RANGE|NOTADR|BANG|WORD1|TRLBAR|ZEROR),
  EX(kCmdStartinsert,     "startinsert",  ex_startinsert,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStartgreplace,   "startgreplace", ex_startinsert,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStartreplace,    "startreplace", ex_startinsert,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStopinsert,      "stopinsert",   ex_stopinsert,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStjump,          "stjump",       ex_stag,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdStselect,        "stselect",     ex_stag,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdSunhide,         "sunhide",      ex_buffer_all,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSunmap,          "sunmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSunmenu,         "sunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSuspend,         "suspend",      ex_stop,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG|CMDWIN),
  EX(kCmdSview,           "sview",        ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSwapname,        "swapname",     ex_swapname,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdSyntax,          "syntax",       ex_syntax,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM|CMDWIN),
  EX(kCmdSyntime,         "syntime",      ex_syntime,
     ARG_SYNTIME_ACTION, ARGS_SYNTIME,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdSyncbind,        "syncbind",     ex_syncbind,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdT,               "t",            ex_copymove,
     ARG_ADDR_ADDR, ARGS_ADDR,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdTNext,           "tNext",        ex_tag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTag,             "tag",          ex_tag,
     ARG_REG_REG, ARGS_REG,
     RANGE|NOTADR|BANG|WORD1|TRLBAR|ZEROR),
  EX(kCmdTags,            "tags",         do_tags,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdTab,             "tab",          ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdTabclose,        "tabclose",     ex_tabclose,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|BANG|TRLBAR|CMDWIN),
  EX(kCmdTabdo,           "tabdo",        ex_listdo,
     ARG_DO_CMD, ARGS_DO,
     NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdTabedit,         "tabedit",      ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdTabfind,         "tabfind",      ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|NEEDARG|TRLBAR),
  EX(kCmdTabfirst,        "tabfirst",     ex_tabnext,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTabmove,         "tabmove",      ex_tabmove,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|ZEROR|EXTRA|NOSPC|TRLBAR),
  EX(kCmdTablast,         "tablast",      ex_tabnext,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTabnext,         "tabnext",      ex_tabnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdTabnew,          "tabnew",       ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdTabonly,         "tabonly",      ex_tabonly,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdTabprevious,     "tabprevious",  ex_tabnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdTabNext,         "tabNext",      ex_tabnext,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdTabrewind,       "tabrewind",    ex_tabnext,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTabs,            "tabs",         ex_tabs,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdTcl,             "tcl",          ex_tcl,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdTcldo,           "tcldo",        ex_tcldo,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdTclfile,         "tclfile",      ex_tclfile,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdTearoff,         "tearoff",      ex_tearoff,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     NEEDARG|EXTRA|TRLBAR|NOTRLCOM|CMDWIN),
  EX(kCmdTfirst,          "tfirst",       ex_tag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdThrow,           "throw",        ex_throw,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdTjump,           "tjump",        ex_tag,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdTlast,           "tlast",        ex_tag,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdTmenu,           "tmenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdTnext,           "tnext",        ex_tag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTopleft,         "topleft",      ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdTprevious,       "tprevious",    ex_tag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTrewind,         "trewind",      ex_tag,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTry,             "try",          ex_try,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdTselect,         "tselect",      ex_tag,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdTunmenu,         "tunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUndo,            "undo",         ex_undo,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|ZEROR|TRLBAR|CMDWIN),
  EX(kCmdUndojoin,        "undojoin",     ex_undojoin,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdUndolist,        "undolist",     ex_undolist,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdUnabbreviate,    "unabbreviate", ex_abbreviate,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUnhide,          "unhide",       ex_buffer_all,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdUnlet,           "unlet",        ex_unlet,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdUnlockvar,       "unlockvar",    ex_lockvar,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdUnmap,           "unmap",        ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUnmenu,          "unmenu",       ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUnsilent,        "unsilent",     ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN | ISMODIFIER),
  EX(kCmdUpdate,          "update",       ex_update,
     ARG_W_SHELL, ARGS_W,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR),
  EX(kCmdVglobal,         "vglobal",      ex_global,
     ARG_G_CMD, ARGS_G,
     RANGE|WHOLEFOLD|EXTRA|DFLALL|CMDWIN),
  EX(kCmdVersion,         "version",      ex_version,
     ARG_NO_ARGS, ARGS_NO,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdVerbose,         "verbose",      ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|RANGE|NOTADR|EXTRA|NOTRLCOM|SBOXOK|CMDWIN | ISMODIFIER),
  EX(kCmdVertical,        "vertical",     ex_wrongmodifier,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdVisual,          "visual",       ex_edit,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdView,            "view",         ex_edit,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdVimgrep,         "vimgrep",      ex_vimgrep,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdVimgrepadd,      "vimgrepadd",   ex_vimgrep,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdViusage,         "viusage",      ex_viusage,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdVmap,            "vmap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVmapclear,       "vmapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdVmenu,           "vmenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVnoremap,        "vnoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVnew,            "vnew",         ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdVnoremenu,       "vnoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVsplit,          "vsplit",       ex_splitview,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdVunmap,          "vunmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVunmenu,         "vunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdWrite,           "write",        ex_write,
     ARG_W_SHELL, ARGS_W,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN),
  EX(kCmdWNext,           "wNext",        ex_wnext,
     ARG_WN_ENC, ARGS_WN,
     RANGE|WHOLEFOLD|NOTADR|BANG|FILE1|ARGOPT|TRLBAR),
  EX(kCmdWall,            "wall",         do_wqall,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdWhile,           "while",        ex_while,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdWinsize,         "winsize",      ex_winsize,
     ARG_WINSIZE_HEIGHT, ARGS_WINSIZE,
     EXTRA|NEEDARG|TRLBAR),
  EX(kCmdWincmd,          "wincmd",       ex_wincmd,
     ARG_WINCMD_CHAR, ARGS_WINCMD,
     NEEDARG|WORD1|RANGE|NOTADR),
  EX(kCmdWindo,           "windo",        ex_listdo,
     ARG_DO_CMD, ARGS_DO,
     BANG|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdWinpos,          "winpos",       ex_winpos,
     ARG_WINSIZE_HEIGHT, ARGS_WINSIZE,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdWnext,           "wnext",        ex_wnext,
     ARG_WN_ENC, ARGS_WN,
     RANGE|NOTADR|BANG|FILE1|ARGOPT|TRLBAR),
  EX(kCmdWprevious,       "wprevious",    ex_wnext,
     ARG_WN_ENC, ARGS_WN,
     RANGE|NOTADR|BANG|FILE1|ARGOPT|TRLBAR),
  EX(kCmdWq,              "wq",           ex_exit,
     ARG_EXIT_ENC, ARGS_EXIT,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR),
  EX(kCmdWqall,           "wqall",        do_wqall,
     ARG_WQA_ENC, ARGS_WQA,
     BANG|FILE1|ARGOPT|DFLALL|TRLBAR),
  EX(kCmdWsverb,          "wsverb",       ex_wsverb,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTADR|NEEDARG),
  EX(kCmdWundo,           "wundo",        ex_wundo,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|FILE1),
  EX(kCmdWviminfo,        "wviminfo",     ex_viminfo,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdXit,             "xit",          ex_exit,
     ARG_EXIT_ENC, ARGS_EXIT,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN),
  EX(kCmdXall,            "xall",         do_wqall,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdXmap,            "xmap",         ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXmapclear,       "xmapclear",    ex_mapclear,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdXmenu,           "xmenu",        ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXnoremap,        "xnoremap",     ex_map,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXnoremenu,       "xnoremenu",    ex_menu,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXunmap,          "xunmap",       ex_unmap,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXunmenu,         "xunmenu",      ex_menu,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdYank,            "yank",         ex_operators,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|REGSTR|COUNT|TRLBAR|CMDWIN),
  EX(kCmdZ,               "z",            ex_z,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|WHOLEFOLD|EXTRA|EXFLAGS|TRLBAR|CMDWIN),

  /* commands that don't start with a lowercase letter */
  EX(kCmdBang,            "!",            ex_bang,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|WHOLEFOLD|BANG|FILES|CMDWIN),
  EX(kCmdPound,           "#",            ex_print,
     ARG_LIST_FLAGS, ARGS_LIST,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdAnd,             "&",            do_sub,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdStar,            "*",            ex_at,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLshift,          "<",            ex_operators,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdEqual,           "=",            ex_equal,
     ARG_LIST_FLAGS, ARGS_LIST,
     RANGE|TRLBAR|DFLALL|EXFLAGS|CMDWIN),
  EX(kCmdRshift,          ">",            ex_operators,
     ARG_LIST_FLAGS, ARGS_LIST,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdAt,              "@",            ex_at,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdUpNext,          "Next",         ex_previous,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdUpPrint,         "Print",        ex_print,
     ARG_LIST_FLAGS, ARGS_LIST,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdX,               "X",            ex_X,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTilde,           "~",            do_sub,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdHashbangComment, "#!",           NULL,
     ARG_NAME_NAME, ARGS_NAME,
     0),
  EX(kCmdComment,         "\"",           NULL,
     ARG_NAME_NAME, ARGS_NAME,
     0),
  EX(kCmdSyntaxError,     NULL,           NULL,
     ARG_ERROR_LINESTR, ARGS_ERROR,
     0),
#ifndef DO_DECLARE_EXCMD
  kCmdSIZE,             /* MUST be after all real commands! */
  kCmdUSER = -1,        /* User-defined command */
  kCmdUSER_BUF = -2     /* User-defined command local to buffer */
#endif
}
#ifndef DO_DECLARE_EXCMD
CommandType
#endif
;
#endif
