/* vi:set ts=8 sts=4 sw=4:
 *
 * VIM - Vi IMproved	by Bram Moolenaar
 *
 * Do ":help uganda"  in Vim to read copying and usage conditions.
 * Do ":help credits" in Vim to see a list of people who contributed.
 */

/*
 * This file defines the Ex commands.
 * When DO_DECLARE_EXCMD is defined, the table with ex command names and
 * options results.
 * When DO_DECLARE_EXCMD is NOT defined, the enum with all the Ex commands
 * results.
 * This clever trick was invented by Ron Aaron.
 */

/*
 * When adding an Ex command:
 * 1. Add an entry in the table below.  Keep it sorted on the shortest
 *    version of the command name that works.  If it doesn't start with a
 *    lower case letter, add it at the end.
 * 2. Add a "case: kCmdXxx" in the big switch in ex_docmd.c.
 * 3. Add an entry in the index for Ex commands at ":help ex-cmd-index".
 * 4. Add documentation in ../doc/xxx.txt.  Add a tag for both the short and
 *    long name of the command.
 */

#if (defined(DO_DECLARE_EXCMD) && !defined(NEOVIM_CMD_DEF_H_DECLARED)) || (!defined(DO_DECLARE_EXCMD) && !defined(NEOVIM_CMD_DEF_H_DEFINED_ENUM))
#ifdef DO_DECLARE_EXCMD
# define NEOVIM_CMD_DEF_H_DECLARED
#else
# define NEOVIM_CMD_DEF_H_DEFINED_ENUM
#endif

#include <stdint.h>
#include "cmd.h"
#include "cmd_arg_constants.h"

#ifdef RANGE
# undef RANGE                   /* SASC on Amiga defines it */
#endif

#define RANGE           0x001   // allow a linespecs
#define BANG            0x002   // allow a ! after the command name
#define EXTRA           0x004   // allow extra args after command name
#define XFILE           0x008   // expand wildcards in extra part
#define NOSPC           0x010   // no spaces allowed in the extra part
#define DFLALL          0x020   // default file range is 1,$
#define WHOLEFOLD       0x040   // extend range to include whole fold also
                                // when less than two numbers given
#define NEEDARG         0x080   // argument required
#define TRLBAR          0x100   // check for trailing vertical bar
#define REGSTR          0x200   // allow "x for register designation
#define COUNT           0x400   // allow count in argument, after command
#define NOTRLCOM        0x800   // no trailing comment allowed
#define ZEROR          0x1000   // zero line number allowed
#define USECTRLV       0x2000   // do not remove CTRL-V from argument
#define NOTADR         0x4000   // number before command is not an address
#define EDITCMD        0x8000   // allow "+command" argument
#define BUFNAME       0x10000L  // accepts buffer name
#define BUFUNL        0x20000L  // accepts unlisted buffer too
#define ARGOPT        0x40000L  // allow "++opt=val" argument
#define SBOXOK        0x80000L  // allowed in the sandbox
#define CMDWIN       0x100000L  // allowed in cmdline window
#define MODIFY       0x200000L  // forbidden in non-'modifiable' buffer
#define EXFLAGS      0x400000L  // allow flags after count in argument

#define ISMODIFIER   0x800000L  // is a modifier command
#define SHELLARG    0x1000000L  // :read !cmd/:w !cmd : allows shell arguments

#define FILES   (XFILE | EXTRA) // multiple extra files allowed
#define WORD1   (EXTRA | NOSPC) // one extra word allowed
#define FILE1   (FILES | NOSPC) // 1 file allowed, defaults to current file

#ifndef DO_DECLARE_EXCMD
typedef struct command_definition CommandDefinition;
#endif

/*
 * This array maps ex command names to command codes.
 * The order in which command names are listed below is significant --
 * ambiguous abbreviations are always resolved to be the first possible match
 * (e.g. "r" is taken to mean "read", not "rewind", because "read" comes
 * before "rewind").
 * Not supported commands are included to avoid ambiguities.
 */
#ifdef EX
# undef EX          /* just in case */
#endif
#ifdef DO_DECLARE_EXCMD
# define CMDDEF(type) cmddefs[type - 1]
# define EX(idx, name, func, last_arg, args, flags) \
    {(char_u *)name, \
     (uint_least32_t) (flags), \
     last_arg + 1, \
     (CommandArgType[]) args, \
     func}

static struct command_definition {
  char_u      *name;          // name of the command
  uint_least32_t flags;       // flags declared above
  size_t num_args;            // number of arguments
  CommandArgType *arg_types;  // argument types
  args_parser parse;          // argument parsing function
}
#define NOFUNC NULL
cmddefs[] =
#else
# define EX(idx, name, func, last_arg, args, flags) idx
typedef enum
#endif
{
#ifndef DO_DECLARE_EXCMD
  kCmdUnknown = 0,
#endif
  EX(kCmdAppend,          "append",       NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     BANG|RANGE|ZEROR|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdAbbreviate,      "abbreviate",   NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdAbclear,         "abclear",      NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdAboveleft,       "aboveleft",    NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdAll,             "all",          NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdAmenu,           "amenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdAnoremenu,       "anoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdArgs,            "args",         NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArgadd,          "argadd",       NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|RANGE|NOTADR|ZEROR|FILES|TRLBAR),
  EX(kCmdArgdelete,       "argdelete",    NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|FILES|TRLBAR),
  EX(kCmdArgdo,           "argdo",        NULL,
     ARG_DO_CMD, ARGS_DO,
     BANG|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdArgedit,         "argedit",      NULL,
     ARG_E_CMD, ARGS_E,
     BANG|NEEDARG|RANGE|NOTADR|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArgglobal,       "argglobal",    NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArglocal,        "arglocal",     NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdArgument,        "argument",     NULL,
     ARG_E_CMD, ARGS_E,
     BANG|RANGE|NOTADR|COUNT|EXTRA|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdAscii,           "ascii",        NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdAutocmd,         "autocmd",      NULL,
     ARG_AU_CMD, ARGS_AU,
     BANG|EXTRA|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdAugroup,         "augroup",      NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdAunmenu,         "aunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdBuffer,          "buffer",       NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|TRLBAR),
  EX(kCmdBNext,           "bNext",        NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBall,            "ball",         NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  /* +lnum will be recorded in range */
  EX(kCmdBadd,            "badd",         NULL,
     ARG_SO_FILES, ARGS_SO,
     NEEDARG|FILE1|EDITCMD|TRLBAR|CMDWIN),
  EX(kCmdBdelete,         "bdelete",      NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR),
  EX(kCmdBehave,          "behave",       NULL,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdBelowright,      "belowright",   NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdBfirst,          "bfirst",       NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|TRLBAR),
  EX(kCmdBlast,           "blast",        NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|TRLBAR),
  EX(kCmdBmodified,       "bmodified",    NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBnext,           "bnext",        NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBotright,        "botright",     NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdBprevious,       "bprevious",    NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdBrewind,         "brewind",      NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|TRLBAR),
  EX(kCmdBreak,           "break",        NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdBreakadd,        "breakadd",     NULL,
     ARG_BREAK_NAME, ARGS_BREAK,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdBreakdel,        "breakdel",     NULL,
     ARG_BREAK_NAME, ARGS_BREAK,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdBreaklist,       "breaklist",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdBrowse,          "browse",       NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|CMDWIN | ISMODIFIER),
  EX(kCmdBuffers,         "buffers",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdBufdo,           "bufdo",        NULL,
     ARG_DO_CMD, ARGS_DO,
     BANG|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdBunload,         "bunload",      NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR),
  EX(kCmdBwipeout,        "bwipeout",     NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|TRLBAR),
  EX(kCmdChange,          "change",       NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     BANG|WHOLEFOLD|RANGE|COUNT|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdCNext,           "cNext",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCNfile,          "cNfile",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCabbrev,         "cabbrev",      NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCabclear,        "cabclear",     NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdCaddbuffer,      "caddbuffer",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdCaddexpr,        "caddexpr",     NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdCaddfile,        "caddfile",     NULL,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdCall,            "call",         NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     RANGE|NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdCatch,           "catch",        NULL,
     ARG_REG_REG, ARGS_REG,
     EXTRA|SBOXOK|CMDWIN),
  EX(kCmdCbuffer,         "cbuffer",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdCc,              "cc",           NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCclose,          "cclose",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdCd,              "cd",           NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdCenter,          "center",       NULL,
     ARG_CENTER_WIDTH, ARGS_CENTER,
     TRLBAR|RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdCexpr,           "cexpr",        NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR|BANG),
  EX(kCmdCfile,           "cfile",        NULL,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1|BANG),
  EX(kCmdCfirst,          "cfirst",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCgetfile,        "cgetfile",     NULL,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdCgetbuffer,      "cgetbuffer",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdCgetexpr,        "cgetexpr",     NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdChdir,           "chdir",        NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdChanges,         "changes",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdCheckpath,       "checkpath",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG|CMDWIN),
  EX(kCmdChecktime,       "checktime",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BUFNAME|COUNT|EXTRA|TRLBAR),
  EX(kCmdClist,           "clist",        NULL,
     ARG_CLIST_LAST, ARGS_CLIST,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdClast,           "clast",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdClose,           "close",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdCmap,            "cmap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCmapclear,       "cmapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdCmenu,           "cmenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCnext,           "cnext",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCnewer,          "cnewer",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdCnfile,          "cnfile",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCnoremap,        "cnoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCnoreabbrev,     "cnoreabbrev",  NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCnoremenu,       "cnoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCopy,            "copy",         NULL,
     ARG_ADDR_ADDR, ARGS_ADDR,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdColder,          "colder",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdColorscheme,     "colorscheme",  NULL,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdCommand,         "command",      NULL,
     ARG_CMD_CMD, ARGS_CMD,
     EXTRA|BANG|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdComclear,        "comclear",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdCompiler,        "compiler",     NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1|CMDWIN),
  EX(kCmdContinue,        "continue",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdConfirm,         "confirm",      NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|CMDWIN | ISMODIFIER),
  EX(kCmdCopen,           "copen",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdCprevious,       "cprevious",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCpfile,          "cpfile",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCquit,           "cquit",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG),
  EX(kCmdCrewind,         "crewind",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdCscope,          "cscope",       NULL,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM|XFILE),
  EX(kCmdCstag,           "cstag",        NULL,
     ARG_CSTAG_TAG, ARGS_CSTAG,
     BANG|TRLBAR|WORD1),
  EX(kCmdCunmap,          "cunmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCunabbrev,       "cunabbrev",    NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCunmenu,         "cunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdCwindow,         "cwindow",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdDelete,          "delete",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|REGSTR|COUNT|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdDelmarks,        "delmarks",     NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDebug,           "debug",        NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdDebuggreedy,     "debuggreedy",  NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|ZEROR|TRLBAR|CMDWIN),
  EX(kCmdDelcommand,      "delcommand",   NULL,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdDelfunction,     "delfunction",  NULL,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|WORD1|CMDWIN),
  EX(kCmdDisplay,         "display",      NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdDiffupdate,      "diffupdate",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdDiffget,         "diffget",      NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|EXTRA|TRLBAR|MODIFY),
  EX(kCmdDiffoff,         "diffoff",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdDiffpatch,       "diffpatch",    NULL,
     ARG_SO_FILES, ARGS_SO,
     EXTRA|FILE1|TRLBAR|MODIFY),
  EX(kCmdDiffput,         "diffput",      NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|EXTRA|TRLBAR),
  EX(kCmdDiffsplit,       "diffsplit",    NULL,
     ARG_SO_FILES, ARGS_SO,
     EXTRA|FILE1|TRLBAR),
  EX(kCmdDiffthis,        "diffthis",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdDigraphs,        "digraphs",     NULL,
     ARG_DIG_CHARS, ARGS_DIG,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDjump,           "djump",        NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdDlist,           "dlist",        NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdDoautocmd,       "doautocmd",    NULL,
     ARG_DOAU_FNAME, ARGS_DOAU,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDoautoall,       "doautoall",    NULL,
     ARG_DOAU_FNAME, ARGS_DOAU,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdDrop,            "drop",         NULL,
     ARG_E_CMD, ARGS_E,
     FILES|EDITCMD|NEEDARG|ARGOPT|TRLBAR),
  EX(kCmdDsearch,         "dsearch",      NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdDsplit,          "dsplit",       NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdEdit,            "edit",         NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdEarlier,         "earlier",      NULL,
     ARG_NAME_NAME, ARGS_NAME,
     TRLBAR|EXTRA|NOSPC|CMDWIN),
  EX(kCmdEcho,            "echo",         NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEchoerr,         "echoerr",      NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEchohl,          "echohl",       NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEchomsg,         "echomsg",      NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEchon,           "echon",        NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdElse,            "else",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdElseif,          "elseif",       NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdEmenu,           "emenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     NEEDARG|EXTRA|TRLBAR|NOTRLCOM|RANGE|NOTADR|CMDWIN),
  EX(kCmdEndif,           "endif",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEndfunction,     "endfunction",  NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdEndfor,          "endfor",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEndtry,          "endtry",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEndwhile,        "endwhile",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdEnew,            "enew",         NULL,
     ARG_E_CMD, ARGS_E,
     BANG|TRLBAR),
  EX(kCmdEx,              "ex",           NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdExecute,         "execute",      NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdExit,            "exit",         NULL,
     ARG_EXIT_ENC, ARGS_EXIT,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN),
  EX(kCmdExusage,         "exusage",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdFile,            "file",         NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|NOTADR|ZEROR|BANG|FILE1|TRLBAR),
  EX(kCmdFiles,           "files",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdFiletype,        "filetype",     NULL,
     ARG_FT_FLAGS, ARGS_FT,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdFind,            "find",         NULL,
     ARG_E_CMD, ARGS_E,
     RANGE|NOTADR|BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdFinally,         "finally",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFinish,          "finish",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFirst,           "first",        NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdFixdel,          "fixdel",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdFold,            "fold",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFoldclose,       "foldclose",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|BANG|WHOLEFOLD|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFolddoopen,      "folddoopen",   NULL,
     ARG_DO_CMD, ARGS_DO,
     RANGE|DFLALL|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdFolddoclosed,    "folddoclosed", NULL,
     ARG_DO_CMD, ARGS_DO,
     RANGE|DFLALL|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdFoldopen,        "foldopen",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|BANG|WHOLEFOLD|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdFor,             "for",          NULL,
     ARG_ASSIGN_RHS, ARGS_ASSIGN,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdFunction,        "function",     NULL,
     ARG_FUNC_BODY, ARGS_FUNC,
     EXTRA|BANG|CMDWIN),
  EX(kCmdGlobal,          "global",       NULL,
     ARG_G_CMD, ARGS_G,
     RANGE|WHOLEFOLD|BANG|EXTRA|DFLALL|SBOXOK|CMDWIN),
  EX(kCmdGoto,            "goto",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdGrep,            "grep",         NULL,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdGrepadd,         "grepadd",      NULL,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdGui,             "gui",          NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR|CMDWIN),
  EX(kCmdGvim,            "gvim",         NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILES|EDITCMD|ARGOPT|TRLBAR|CMDWIN),
  EX(kCmdHelp,            "help",         NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|EXTRA|NOTRLCOM),
  EX(kCmdHelpfind,        "helpfind",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     EXTRA|NOTRLCOM),
  EX(kCmdHelpgrep,        "helpgrep",     NULL,
     ARG_HELPG_LANG, ARGS_HELPG,
     EXTRA|NOTRLCOM|NEEDARG),
  /* ++t is in count */
  EX(kCmdHelptags,        "helptags",     NULL,
     ARG_SO_FILES, ARGS_SO,
     NEEDARG|FILES|TRLBAR|CMDWIN),
  EX(kCmdHardcopy,        "hardcopy",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|COUNT|EXTRA|TRLBAR|DFLALL|BANG),
  EX(kCmdHighlight,       "highlight",    NULL,
     ARG_HI_GUISP, ARGS_HI,
     BANG|EXTRA|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdHide,            "hide",         NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     BANG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdHistory,         "history",      NULL,
     ARG_HIST_LAST, ARGS_HIST,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdInsert,          "insert",       NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     BANG|RANGE|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdIabbrev,         "iabbrev",      NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIabclear,        "iabclear",     NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdIf,              "if",           NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdIjump,           "ijump",        NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdIlist,           "ilist",        NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdImap,            "imap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdImapclear,       "imapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdImenu,           "imenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdInoremap,        "inoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdInoreabbrev,     "inoreabbrev",  NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdInoremenu,       "inoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIntro,           "intro",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdIsearch,         "isearch",      NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdIsplit,          "isplit",       NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|DFLALL|WHOLEFOLD|EXTRA),
  EX(kCmdIunmap,          "iunmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIunabbrev,       "iunabbrev",    NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdIunmenu,         "iunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdJoin,            "join",         NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdJumps,           "jumps",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdK,               "k",            NULL,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WORD1|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdKeepmarks,       "keepmarks",    NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdKeepjumps,       "keepjumps",    NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdKeeppatterns,    "keeppatterns", NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdKeepalt,         "keepalt",      NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdList,            "list",         NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdLNext,           "lNext",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLNfile,          "lNfile",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLast,            "last",         NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdLanguage,        "language",     NULL,
     ARG_LANG_LANG, ARGS_LANG,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLaddexpr,        "laddexpr",     NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdLaddbuffer,      "laddbuffer",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdLaddfile,        "laddfile",     NULL,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdLater,           "later",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     TRLBAR|EXTRA|NOSPC|CMDWIN),
  EX(kCmdLbuffer,         "lbuffer",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdLcd,             "lcd",          NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdLchdir,          "lchdir",       NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdLclose,          "lclose",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLcscope,         "lcscope",      NULL,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM|XFILE),
  EX(kCmdLeft,            "left",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdLeftabove,       "leftabove",    NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdLet,             "let",          NULL,
     ARG_ASSIGN_RHS, ARGS_ASSIGN,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdLexpr,           "lexpr",        NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR|BANG),
  EX(kCmdLfile,           "lfile",        NULL,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1|BANG),
  EX(kCmdLfirst,          "lfirst",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLgetfile,        "lgetfile",     NULL,
     ARG_SO_FILES, ARGS_SO,
     TRLBAR|FILE1),
  EX(kCmdLgetbuffer,      "lgetbuffer",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|WORD1|TRLBAR),
  EX(kCmdLgetexpr,        "lgetexpr",     NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     NEEDARG|WORD1|NOTRLCOM|TRLBAR),
  EX(kCmdLgrep,           "lgrep",        NULL,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLgrepadd,        "lgrepadd",     NULL,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLhelpgrep,       "lhelpgrep",    NULL,
     ARG_HELPG_LANG, ARGS_HELPG,
     EXTRA|NOTRLCOM|NEEDARG),
  EX(kCmdLl,              "ll",           NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLlast,           "llast",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLlist,           "llist",        NULL,
     ARG_CLIST_LAST, ARGS_CLIST,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLmap,            "lmap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdLmapclear,       "lmapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLmake,           "lmake",        NULL,
     ARG_SHELL_ARGS, ARGS_SHELL,
     BANG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLnoremap,        "lnoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdLnext,           "lnext",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLnewer,          "lnewer",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLnfile,          "lnfile",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLoadview,        "loadview",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     FILE1|TRLBAR),
  EX(kCmdLoadkeymap,      "loadkeymap",   NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     CMDWIN),
  EX(kCmdLockmarks,       "lockmarks",    NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdLockvar,         "lockvar",      NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdLolder,          "lolder",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLopen,           "lopen",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLprevious,       "lprevious",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLpfile,          "lpfile",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLrewind,         "lrewind",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR|BANG),
  EX(kCmdLtag,            "ltag", NULL,
     ARG_REG_REG, ARGS_REG,
     NOTADR|TRLBAR|BANG|WORD1),
  EX(kCmdLua,             "lua",          NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdLuado,           "luado",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdLuafile,         "luafile",      NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdLunmap,          "lunmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdLvimgrep,        "lvimgrep",     NULL,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLvimgrepadd,     "lvimgrepadd",  NULL,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdLwindow,         "lwindow",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdLs,              "ls",           NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdMove,            "move",         NULL,
     ARG_ADDR_ADDR, ARGS_ADDR,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdMark,            "mark",         NULL,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WORD1|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdMake,            "make",         NULL,
     ARG_SHELL_ARGS, ARGS_SHELL,
     BANG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdMap,             "map",          NULL,
     ARG_MAP_RHS, ARGS_MAP,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdMapclear,        "mapclear",     NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|BANG|TRLBAR|CMDWIN),
  EX(kCmdMarks,           "marks",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdMatch,           "match",        NULL,
     ARG_MATCH_REG, ARGS_MATCH,
     RANGE|NOTADR|EXTRA|CMDWIN),
  EX(kCmdMenu,            "menu",         NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdMenutranslate,   "menutranslate", NULL,
     ARG_MT_TO, ARGS_MT,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdMessages,        "messages",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdMkexrc,          "mkexrc",       NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdMksession,       "mksession",    NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR),
  EX(kCmdMkspell,         "mkspell",      NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdMkvimrc,         "mkvimrc",      NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdMkview,          "mkview",       NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR),
  EX(kCmdMode,            "mode",         NULL,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdMzscheme,        "mzscheme",     NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|DFLALL|NEEDARG|CMDWIN|SBOXOK),
  EX(kCmdMzfile,          "mzfile",       NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdNext,            "next",         NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     RANGE|NOTADR|BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdNbkey,           "nbkey",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTADR|NEEDARG),
  EX(kCmdNbclose,         "nbclose",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdNbstart,         "nbstart",      NULL,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdNew,             "new",          NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdNmap,            "nmap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNmapclear,       "nmapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdNmenu,           "nmenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNnoremap,        "nnoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNnoremenu,       "nnoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNoremap,         "noremap",      NULL,
     ARG_MAP_RHS, ARGS_MAP,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNoautocmd,       "noautocmd",    NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdNohlsearch,      "nohlsearch",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdNoreabbrev,      "noreabbrev",   NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNoremenu,        "noremenu",     NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNormal,          "normal",       NULL,
     ARG_NORMAL_STR, ARGS_NORMAL,
     RANGE|BANG|EXTRA|NEEDARG|NOTRLCOM|USECTRLV|SBOXOK|CMDWIN),
  EX(kCmdNumber,          "number",       NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdNunmap,          "nunmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdNunmenu,         "nunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOpen,            "open",         NULL,
     ARG_REG_REG, ARGS_REG,
     RANGE|BANG|EXTRA),
  EX(kCmdOldfiles,        "oldfiles",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdOmap,            "omap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOmapclear,       "omapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdOmenu,           "omenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOnly,            "only",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdOnoremap,        "onoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOnoremenu,       "onoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOptions,         "options",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdOunmap,          "ounmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOunmenu,         "ounmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdOwnsyntax,       "ownsyntax",    NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdPrint,           "print",        NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|SBOXOK),
  EX(kCmdPclose,          "pclose",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdPerl,            "perl",         NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|DFLALL|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdPerldo,          "perldo",       NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|EXTRA|DFLALL|NEEDARG|CMDWIN),
  EX(kCmdPedit,           "pedit",        NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdPop,             "pop",          NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|COUNT|TRLBAR|ZEROR),
  EX(kCmdPopup,           "popup",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     NEEDARG|EXTRA|BANG|TRLBAR|NOTRLCOM|CMDWIN),
  EX(kCmdPpop,            "ppop",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|COUNT|TRLBAR|ZEROR),
  EX(kCmdPreserve,        "preserve",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdPrevious,        "previous",     NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdPromptfind,      "promptfind",   NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|CMDWIN),
  EX(kCmdPromptrepl,      "promptrepl",   NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|CMDWIN),
  EX(kCmdProfile,         "profile",      NULL,
     ARG_PROFILE_PAT, ARGS_PROFILE,
     BANG|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdProfdel,         "profdel",      NULL,
     ARG_PROFILE_PAT, ARGS_PROFILE,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdPsearch,         "psearch",      NULL,
     ARG_REG_REG, ARGS_REG,
     BANG|RANGE|WHOLEFOLD|DFLALL|EXTRA),
  EX(kCmdPtag,            "ptag",         NULL,
     ARG_REG_REG, ARGS_REG,
     RANGE|NOTADR|BANG|WORD1|TRLBAR|ZEROR),
  EX(kCmdPtNext,          "ptNext",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtfirst,         "ptfirst",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtjump,          "ptjump",       NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdPtlast,          "ptlast",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdPtnext,          "ptnext",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtprevious,      "ptprevious",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtrewind,        "ptrewind",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdPtselect,        "ptselect",     NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdPut,             "put",          NULL,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|BANG|REGSTR|TRLBAR|ZEROR|CMDWIN|MODIFY),
  EX(kCmdPwd,             "pwd",          NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdPython,          "python",       NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPydo,            "pydo",         NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPyfile,          "pyfile",       NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdPy3,             "py3",          NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPy3do,           "py3do",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPython3,         "python3",      NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdPy3file,         "py3file",      NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdQuit,            "quit",         NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdQuitall,         "quitall",      NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR),
  EX(kCmdQall,            "qall",         NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdRead,            "read",         NULL,
     ARG_W_SHELL, ARGS_W,
     BANG|RANGE|WHOLEFOLD|FILE1|ARGOPT|TRLBAR|ZEROR|CMDWIN|MODIFY | SHELLARG),
  EX(kCmdRecover,         "recover",      NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR),
  EX(kCmdRedo,            "redo",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdRedir,           "redir",        NULL,
     ARG_REDIR_VAR, ARGS_REDIR,
     BANG|FILES|TRLBAR|CMDWIN),
  EX(kCmdRedraw,          "redraw",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdRedrawstatus,    "redrawstatus", NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdRegisters,       "registers",    NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTRLCOM|TRLBAR|CMDWIN),
  EX(kCmdResize,          "resize",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|TRLBAR|WORD1),
  EX(kCmdRetab,           "retab",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|RANGE|WHOLEFOLD|DFLALL|BANG|WORD1|CMDWIN|MODIFY),
  EX(kCmdReturn,          "return",       NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdRewind,          "rewind",       NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdRight,           "right",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdRightbelow,      "rightbelow",   NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdRuntime,         "runtime",      NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|FILES|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdRuby,            "ruby",         NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdRubydo,          "rubydo",       NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdRubyfile,        "rubyfile",     NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdRundo,           "rundo",        NULL,
     ARG_SO_FILES, ARGS_SO,
     NEEDARG|FILE1),
  EX(kCmdRviminfo,        "rviminfo",     NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdSubstitute,      "substitute",   NULL,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdSNext,           "sNext",        NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSargument,       "sargument",    NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     BANG|RANGE|NOTADR|COUNT|EXTRA|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSall,            "sall",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSandbox,         "sandbox",      NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdSaveas,          "saveas",       NULL,
     ARG_WN_ENC, ARGS_WN,
     BANG|DFLALL|FILE1|ARGOPT|CMDWIN|TRLBAR),
  EX(kCmdSbuffer,         "sbuffer",      NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|RANGE|NOTADR|BUFNAME|BUFUNL|COUNT|EXTRA|TRLBAR),
  EX(kCmdSbNext,          "sbNext",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSball,           "sball",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbfirst,         "sbfirst",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSblast,          "sblast",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSbmodified,      "sbmodified",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbnext,          "sbnext",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbprevious,      "sbprevious",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSbrewind,        "sbrewind",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdScriptnames,     "scriptnames",  NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdScriptencoding,  "scriptencoding", NULL,
     ARG_NAME_NAME, ARGS_NAME,
     WORD1|TRLBAR|CMDWIN),
  EX(kCmdScscope,         "scscope",      NULL,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM),
  EX(kCmdSet,             "set",          NULL,
     ARG_SET_VALUES, ARGS_SET,
     TRLBAR|EXTRA|CMDWIN|SBOXOK),
  EX(kCmdSetfiletype,     "setfiletype",  NULL,
     ARG_NAME_NAME, ARGS_NAME,
     TRLBAR|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdSetglobal,       "setglobal",    NULL,
     ARG_SET_VALUES, ARGS_SET,
     TRLBAR|EXTRA|CMDWIN|SBOXOK),
  EX(kCmdSetlocal,        "setlocal",     NULL,
     ARG_SET_VALUES, ARGS_SET,
     TRLBAR|EXTRA|CMDWIN|SBOXOK),
  EX(kCmdSfind,           "sfind",        NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSfirst,          "sfirst",       NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdShell,           "shell",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdSimalt,          "simalt",       NULL,
     ARG_SIMALT_CHAR, ARGS_SIMALT,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdSign,            "sign",         NULL,
     ARG_SUBCMD, ARGS_SUBCMD,
     NEEDARG|RANGE|NOTADR|EXTRA|CMDWIN),
  EX(kCmdSilent,          "silent",       NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|BANG|NOTRLCOM|SBOXOK|CMDWIN | ISMODIFIER),
  EX(kCmdSleep,           "sleep",        NULL,
     ARG_SLEEP_SECONDS, ARGS_SLEEP,
     RANGE|NOTADR|COUNT|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdSlast,           "slast",        NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSmagic,          "smagic",       NULL,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdSmap,            "smap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSmapclear,       "smapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdSmenu,           "smenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSnext,           "snext",        NULL,
     ARG_E_CMD, ARGS_E,
     RANGE|NOTADR|BANG|FILES|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSniff,           "sniff",        NULL,
     ARG_SNIFF_SYMBOL, ARGS_SNIFF,
     EXTRA|TRLBAR),
  EX(kCmdSnomagic,        "snomagic",     NULL,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN),
  EX(kCmdSnoremap,        "snoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSnoremenu,       "snoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSource,          "source",       NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdSort,            "sort",         NULL,
     ARG_SORT_REG, ARGS_SORT,
     RANGE|DFLALL|WHOLEFOLD|BANG|EXTRA|NOTRLCOM|MODIFY),
  EX(kCmdSplit,           "split",        NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSpellgood,       "spellgood",    NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|RANGE|NOTADR|NEEDARG|EXTRA|TRLBAR),
  EX(kCmdSpelldump,       "spelldump",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdSpellinfo,       "spellinfo",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSpellrepall,     "spellrepall",  NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdSpellundo,       "spellundo",    NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|RANGE|NOTADR|NEEDARG|EXTRA|TRLBAR),
  EX(kCmdSpellwrong,      "spellwrong",   NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|RANGE|NOTADR|NEEDARG|EXTRA|TRLBAR),
  EX(kCmdSprevious,       "sprevious",    NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSrewind,         "srewind",      NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdStop,            "stop",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG|CMDWIN),
  EX(kCmdStag,            "stag",         NULL,
     ARG_REG_REG, ARGS_REG,
     RANGE|NOTADR|BANG|WORD1|TRLBAR|ZEROR),
  EX(kCmdStartinsert,     "startinsert",  NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStartgreplace,   "startgreplace", NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStartreplace,    "startreplace", NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStopinsert,      "stopinsert",   NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdStjump,          "stjump",       NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdStselect,        "stselect",     NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdSunhide,         "sunhide",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdSunmap,          "sunmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSunmenu,         "sunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdSuspend,         "suspend",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|BANG|CMDWIN),
  EX(kCmdSview,           "sview",        NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdSwapname,        "swapname",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdSyntax,          "syntax",       NULL,
     ARG_SUBCMD, ARGS_SUBCMD,
     EXTRA|NOTRLCOM|CMDWIN),
  EX(kCmdSyntime,         "syntime",      NULL,
     ARG_SYNTIME_ACTION, ARGS_SYNTIME,
     NEEDARG|WORD1|TRLBAR|CMDWIN),
  EX(kCmdSyncbind,        "syncbind",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdT,               "t",            NULL,
     ARG_ADDR_ADDR, ARGS_ADDR,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdTNext,           "tNext",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTag,             "tag",          NULL,
     ARG_REG_REG, ARGS_REG,
     RANGE|NOTADR|BANG|WORD1|TRLBAR|ZEROR),
  EX(kCmdTags,            "tags",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdTab,             "tab",          NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdTabclose,        "tabclose",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|BANG|TRLBAR|CMDWIN),
  EX(kCmdTabdo,           "tabdo",        NULL,
     ARG_DO_CMD, ARGS_DO,
     NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdTabedit,         "tabedit",      NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdTabfind,         "tabfind",      NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|NEEDARG|TRLBAR),
  EX(kCmdTabfirst,        "tabfirst",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTabmove,         "tabmove",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|ZEROR|EXTRA|NOSPC|TRLBAR),
  EX(kCmdTablast,         "tablast",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTabnext,         "tabnext",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdTabnew,          "tabnew",       NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|ZEROR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdTabonly,         "tabonly",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdTabprevious,     "tabprevious",  NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdTabNext,         "tabNext",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdTabrewind,       "tabrewind",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTabs,            "tabs",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdTcl,             "tcl",          NULL,
     ARG_APPEND_LINES, ARGS_APPEND,
     RANGE|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdTcldo,           "tcldo",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|DFLALL|EXTRA|NEEDARG|CMDWIN),
  EX(kCmdTclfile,         "tclfile",      NULL,
     ARG_SO_FILES, ARGS_SO,
     RANGE|FILE1|NEEDARG|CMDWIN),
  EX(kCmdTearoff,         "tearoff",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     NEEDARG|EXTRA|TRLBAR|NOTRLCOM|CMDWIN),
  EX(kCmdTfirst,          "tfirst",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdThrow,           "throw",        NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdTjump,           "tjump",        NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdTlast,           "tlast",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdTmenu,           "tmenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdTnext,           "tnext",        NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTopleft,         "topleft",      NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdTprevious,       "tprevious",    NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTrewind,         "trewind",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|BANG|TRLBAR|ZEROR),
  EX(kCmdTry,             "try",          NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|SBOXOK|CMDWIN),
  EX(kCmdTselect,         "tselect",      NULL,
     ARG_NAME_NAME, ARGS_NAME,
     BANG|TRLBAR|WORD1),
  EX(kCmdTunmenu,         "tunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUndo,            "undo",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|ZEROR|TRLBAR|CMDWIN),
  EX(kCmdUndojoin,        "undojoin",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdUndolist,        "undolist",     NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR|CMDWIN),
  EX(kCmdUnabbreviate,    "unabbreviate", NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUnhide,          "unhide",       NULL,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|NOTADR|COUNT|TRLBAR),
  EX(kCmdUnlet,           "unlet",        NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdUnlockvar,       "unlockvar",    NULL,
     ARG_EXPRS_EXPRS, ARGS_EXPRS,
     BANG|EXTRA|NEEDARG|SBOXOK|CMDWIN),
  EX(kCmdUnmap,           "unmap",        NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUnmenu,          "unmenu",       NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     BANG|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdUnsilent,        "unsilent",     NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM|SBOXOK|CMDWIN | ISMODIFIER),
  EX(kCmdUpdate,          "update",       NULL,
     ARG_W_SHELL, ARGS_W,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR | SHELLARG),
  EX(kCmdVglobal,         "vglobal",      NULL,
     ARG_G_CMD, ARGS_G,
     RANGE|WHOLEFOLD|EXTRA|DFLALL|CMDWIN),
  EX(kCmdVersion,         "version",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdVerbose,         "verbose",      NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|RANGE|NOTADR|EXTRA|NOTRLCOM|SBOXOK|CMDWIN | ISMODIFIER),
  EX(kCmdVertical,        "vertical",     NULL,
     ARG_MODIFIER_CMD, ARGS_MODIFIER,
     NEEDARG|EXTRA|NOTRLCOM | ISMODIFIER),
  EX(kCmdVisual,          "visual",       NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdView,            "view",         NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdVimgrep,         "vimgrep",      NULL,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdVimgrepadd,      "vimgrepadd",   NULL,
     ARG_VIMG_FILES, ARGS_VIMG,
     RANGE|NOTADR|BANG|NEEDARG|EXTRA|NOTRLCOM|TRLBAR|XFILE),
  EX(kCmdViusage,         "viusage",      NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdVmap,            "vmap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVmapclear,       "vmapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdVmenu,           "vmenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVnoremap,        "vnoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVnew,            "vnew",         NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdVnoremenu,       "vnoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVsplit,          "vsplit",       NULL,
     ARG_E_CMD, ARGS_E,
     BANG|FILE1|RANGE|NOTADR|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdVunmap,          "vunmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdVunmenu,         "vunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdWrite,           "write",        NULL,
     ARG_W_SHELL, ARGS_W,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN | SHELLARG),
  EX(kCmdWNext,           "wNext",        NULL,
     ARG_WN_ENC, ARGS_WN,
     RANGE|WHOLEFOLD|NOTADR|BANG|FILE1|ARGOPT|TRLBAR),
  EX(kCmdWall,            "wall",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR|CMDWIN),
  EX(kCmdWhile,           "while",        NULL,
     ARG_EXPR_EXPR, ARGS_EXPR,
     EXTRA|NOTRLCOM|SBOXOK|CMDWIN),
  EX(kCmdWinsize,         "winsize",      NULL,
     ARG_WINSIZE_HEIGHT, ARGS_WINSIZE,
     EXTRA|NEEDARG|TRLBAR),
  EX(kCmdWincmd,          "wincmd",       NULL,
     ARG_WINCMD_CHAR, ARGS_WINCMD,
     NEEDARG|WORD1|RANGE|NOTADR),
  EX(kCmdWindo,           "windo",        NULL,
     ARG_DO_CMD, ARGS_DO,
     BANG|NEEDARG|EXTRA|NOTRLCOM),
  EX(kCmdWinpos,          "winpos",       NULL,
     ARG_WINSIZE_HEIGHT, ARGS_WINSIZE,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdWnext,           "wnext",        NULL,
     ARG_WN_ENC, ARGS_WN,
     RANGE|NOTADR|BANG|FILE1|ARGOPT|TRLBAR),
  EX(kCmdWprevious,       "wprevious",    NULL,
     ARG_WN_ENC, ARGS_WN,
     RANGE|NOTADR|BANG|FILE1|ARGOPT|TRLBAR),
  EX(kCmdWq,              "wq",           NULL,
     ARG_EXIT_ENC, ARGS_EXIT,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR),
  EX(kCmdWqall,           "wqall",        NULL,
     ARG_WQA_ENC, ARGS_WQA,
     BANG|FILE1|ARGOPT|DFLALL|TRLBAR),
  EX(kCmdWsverb,          "wsverb",       NULL,
     ARG_NAME_NAME, ARGS_NAME,
     EXTRA|NOTADR|NEEDARG),
  EX(kCmdWundo,           "wundo",        NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|NEEDARG|FILE1),
  EX(kCmdWviminfo,        "wviminfo",     NULL,
     ARG_SO_FILES, ARGS_SO,
     BANG|FILE1|TRLBAR|CMDWIN),
  EX(kCmdXit,             "xit",          NULL,
     ARG_EXIT_ENC, ARGS_EXIT,
     RANGE|WHOLEFOLD|BANG|FILE1|ARGOPT|DFLALL|TRLBAR|CMDWIN),
  EX(kCmdXall,            "xall",         NULL,
     ARG_NO_ARGS, ARGS_NO,
     BANG|TRLBAR),
  EX(kCmdXmap,            "xmap",         NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXmapclear,       "xmapclear",    NULL,
     ARG_CLEAR_BUFFER, ARGS_CLEAR,
     EXTRA|TRLBAR|CMDWIN),
  EX(kCmdXmenu,           "xmenu",        NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXnoremap,        "xnoremap",     NULL,
     ARG_MAP_RHS, ARGS_MAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXnoremenu,       "xnoremenu",    NULL,
     ARG_MENU_TEXT, ARGS_MENU,
     RANGE|NOTADR|ZEROR|EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXunmap,          "xunmap",       NULL,
     ARG_UNMAP_LHS, ARGS_UNMAP,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdXunmenu,         "xunmenu",      NULL,
     ARG_UNMENU_LHS, ARGS_UNMENU,
     EXTRA|TRLBAR|NOTRLCOM|USECTRLV|CMDWIN),
  EX(kCmdYank,            "yank",         NULL,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|REGSTR|COUNT|TRLBAR|CMDWIN),
  EX(kCmdZ,               "z",            NULL,
     ARG_NAME_NAME, ARGS_NAME,
     RANGE|WHOLEFOLD|EXTRA|EXFLAGS|TRLBAR|CMDWIN),

  /* commands that don't start with a lowercase letter */
  EX(kCmdBang,            "!",            NULL,
     ARG_SHELL_ARGS, ARGS_SHELL,
     RANGE|WHOLEFOLD|BANG|FILES|CMDWIN),
  EX(kCmdPound,           "#",            NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdAnd,             "&",            NULL,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdStar,            "*",            NULL,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdLshift,          "<",            NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdEqual,           "=",            NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|TRLBAR|DFLALL|EXFLAGS|CMDWIN),
  EX(kCmdRshift,          ">",            NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN|MODIFY),
  EX(kCmdAt,              "@",            NULL,
     ARG_MARK_CHAR, ARGS_MARK,
     RANGE|WHOLEFOLD|EXTRA|TRLBAR|CMDWIN),
  EX(kCmdUpNext,          "Next",         NULL,
     ARG_FIRST_CMD, ARGS_FIRST,
     EXTRA|RANGE|NOTADR|COUNT|BANG|EDITCMD|ARGOPT|TRLBAR),
  EX(kCmdUpPrint,         "Print",        NOFUNC,
     ARG_NO_ARGS, ARGS_NO,
     RANGE|WHOLEFOLD|COUNT|EXFLAGS|TRLBAR|CMDWIN),
  EX(kCmdX,               "X",            NULL,
     ARG_NO_ARGS, ARGS_NO,
     TRLBAR),
  EX(kCmdTilde,           "~",            NULL,
     ARG_S_FLAGS, ARGS_S,
     RANGE|WHOLEFOLD|EXTRA|CMDWIN|MODIFY),
  EX(kCmdHashbangComment, "#!",           NULL,
     ARG_NAME_NAME, ARGS_NAME,
     0),
  EX(kCmdComment,         "\"",           NULL,
     ARG_NAME_NAME, ARGS_NAME,
     0),
  EX(kCmdSyntaxError,     NULL,           NULL,
     ARG_ERROR_LINESTR, ARGS_ERROR,
     0),
#ifndef DO_DECLARE_EXCMD
  _kCmdEND,             /* MUST be after all real commands! */
  kCmdUSER = -1,        /* User-defined command */
#endif
}
#ifndef DO_DECLARE_EXCMD
CommandType
#endif
;
#ifndef DO_DECLARE_EXCMD
# define kCmdSIZE (((size_t)_kCmdEND) - 1)
#endif
#endif
