#ifndef NVIM_TRANSLATOR_EXECUTOR_EXECUTOR_H
#define NVIM_TRANSLATOR_EXECUTOR_EXECUTOR_H

#include "nvim/api/private/helpers.h"
#include "nvim/func_attr.h"

// Generated by msgpack-gen.lua
void nlua_add_api_functions(lua_State *lstae) REAL_FATTR_NONNULL_ALL;

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "translator/executor/executor.h.generated.h"
#endif
#endif  // NVIM_TRANSLATOR_EXECUTOR_EXECUTOR_H
