#ifndef NVIM_TRANSLATOR_EXECUTOR_EXECUTOR_H
#define NVIM_TRANSLATOR_EXECUTOR_EXECUTOR_H

#ifdef INCLUDE_GENERATED_DECLARATIONS
# include "translator/executor/executor.h.generated.h"
#endif
#endif  // NVIM_TRANSLATOR_EXECUTOR_EXECUTOR_H
